### ISSUE TITLE
empty zone should always make ticket invalid

### ISSUE THREAD

**Issue by fxbrit** [luco5826/group03-jwticket#1]
empty `vz` or `zone` should always result in `Not Valid` or a similar error.

at the moment, when both are empty we consider the token valid. see below test:
https://github.com/luco5826/group03-jwticket/blob/eff12b58ac5b0f6e54e8550565a2f62d0cd9bfc9/server/src/test/kotlin/it/polito/wa2/group03/server/UnitTests.kt#L106

**Comment by luco5826** [comment]
Hi @fxbrit 

Thank you for submitting an issue! We've worked on it and it should be solved by 8c0ef306ff16a0403d119c2898eaaa159f29b25a .

Let us know if it works and close this issue when you're satisfied!
