### ISSUE TITLE
what about stateless

### ISSUE THREAD

**Issue by fxbrit** [luco5826/group03-jwticket#9]
I created the stateless branch in case we might need it https://github.com/luco5826/group03-jwticket/tree/stateless-service, but do we? if not we can delete it, otherwise I will try to keep in it aligned with the refactors proposed in https://github.com/luco5826/group03-jwticket/pull/7.

**Comment by luco5826** [comment]
I think we could manage the co-existence of 2 implementations in the same branch, whenever needed we could swap the `@Primary` tag on the controller.
TLDR; imo it is safe to delete the alternative branch

**Comment by fxbrit** [comment]
great, I'll do it asap!
